.WIDTH 3072;
.LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

.EXPORT REPORT FILE=$PARAM{'EXPORT_OUTPUT'}

SELECT * FROM $PARAM{'CMSSDB'}.ABNO_INCM_CALC_LOG WHERE ABNO_INCM_CALC_BTCH = '$PARAM{'ABNO_INCM_CALC_BTCH'}';

.QUIT;
