.WIDTH 256;
.LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

INSERT INTO $PARAM{'CMSSDB'}.ABNO_INCM_CALC_OBJ (ABNO_INCM_CALC_BTCH, SEC_CDE)
SELECT '$PARAM{'abno_incm_calc_btch'}', SEC_CDE
FROM	NSOVIEW.CSDC_INTG_SEC_INFO, $PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'}
WHERE S_DATE <= CAST('$PARAM{'s_date'}' AS DATE FORMAT 'YYYYMMDD')
AND	E_DATE > CAST('$PARAM{'e_date'}' AS DATE FORMAT 'YYYYMMDD')
AND	SEC_REG_STS_SORT NOT IN ('2','5')			--证券登记状态类别 2：退市、5：废弃
AND SEC_CDE = ITEM_NBR
;

.QUIT;

