.WIDTH 256;
.LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

DELETE FROM $PARAM{'CMSSDB'}.ABNO_INCM_CALC_OBJ 
WHERE ABNO_INCM_CALC_BTCH = '$PARAM{'abno_incm_calc_btch'}';

INSERT INTO $PARAM{'CMSSDB'}.ABNO_INCM_CALC_OBJ (ABNO_INCM_CALC_BTCH, SEC_CDE)
SELECT DISTINCT '$PARAM{'abno_incm_calc_btch'}', SEC_CDE
FROM	NSOVIEW.CSDC_INTG_SEC_INFO
WHERE SEC_CTG ='11'  --A股
AND MKT_SORT IN ($PARAM{'sec_exch_cde_quot'})
AND E_DATE > CAST('$PARAM{'s_date'}' AS DATE FORMAT 'YYYYMMDD')
;

.QUIT;

