.WIDTH 256;
.LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

DELETE FROM $PARAM{'CMSSDB'}.ABNO_INCM_CALC_INVST WHERE ABNO_INCM_CALC_BTCH = '$PARAM{'abno_incm_calc_btch'}';

-- 导入上传文件中包含的一码通或证券账号。
INSERT INTO $PARAM{'CMSSDB'}.ABNO_INCM_CALC_INVST (ABNO_INCM_CALC_BTCH, PRMT_TYPE, PRMT_VAL)
SELECT '$PARAM{'abno_incm_calc_btch'}', '$PARAM{'invst_sort'}', ITEM_NBR
FROM	$PARAM{'TEMP_DB'}.$PARAM{'LOAD_TBL'}
WHERE ITEM_NBR IS NOT NULL
;

SELECT * FROM $PARAM{'CMSSDB'}.ABNO_INCM_CALC_INVST
WHERE ABNO_INCM_CALC_BTCH = '$PARAM{'abno_incm_calc_btch'}';

-- 将ABNO_INCM_CALC_INVST中一码通对应的证券账号插入ABNO_INCM_CALC_INVST表。
INSERT INTO $PARAM{'CMSSDB'}.ABNO_INCM_CALC_INVST (ABNO_INCM_CALC_BTCH, PRMT_TYPE, PRMT_VAL)
SELECT DISTINCT '$PARAM{'abno_incm_calc_btch'}', '2', A.SEC_ACCT
FROM NsoVIEW.CSDC_INTG_SEC_ACCT A, $PARAM{'CMSSDB'}.ABNO_INCM_CALC_INVST B
WHERE B.ABNO_INCM_CALC_BTCH = '$PARAM{'abno_incm_calc_btch'}'
AND B.PRMT_TYPE = '1'
AND A.OAP_ACCT_NBR = B.PRMT_VAL
AND A.OAP_ACCT_NBR IS NOT NULL
AND TRIM(A.OAP_ACCT_NBR) <> ''
AND A.E_DATE > CAST('$PARAM{'s_date'}' AS DATE FORMAT 'YYYYMMDD')
;
	
.QUIT;

