.WIDTH 512;
.LOGON $PARAM{'HOSTNM'}/$PARAM{'USERNM'},$PARAM{'PASSWD'};

UPDATE $PARAM{'CMSSDB'}.ABNO_INCM_CALC_LOG SET ABNO_INCM_CALC_BTCH_STS = '$PARAM{'abno_incm_calc_btch_sts'}'
WHERE ABNO_INCM_CALC_BTCH = '$PARAM{'abno_incm_calc_btch'}';

.QUIT;
