CREATE SET TABLE WXHDATA.abno_fastld ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      item_nbr VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX ( item_nbr );


CREATE MULTISET TABLE WXHDATA.ABNO_INCM_CALC_INVST ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ABNO_INCM_CALC_BTCH CHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次' NOT NULL,
      PRMT_TYPE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '参数类型' NOT NULL,
      PRMT_VAL VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '参数值' NOT NULL)
UNIQUE PRIMARY INDEX ( ABNO_INCM_CALC_BTCH ,PRMT_VAL );


CREATE MULTISET TABLE WXHDATA.ABNO_INCM_CALC_OBJ ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ABNO_INCM_CALC_BTCH CHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次' NOT NULL,
      SEC_CDE CHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券代码' NOT NULL)
UNIQUE PRIMARY INDEX ( ABNO_INCM_CALC_BTCH ,SEC_CDE );


CREATE MULTISET TABLE WXHDATA.ABNO_INCM_CALC_LOG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ABNO_INCM_CALC_BTCH CHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '统计起始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '统计终止日期' NOT NULL,
      OBJ_TYPE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '标的类型' NOT NULL,
      OBJ_CNTNT VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '标的' NOT NULL,
      INVST_SORT CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '投资者类型' NOT NULL,
      INVST_CNTNT VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '投资者' NOT NULL,
      SEC_EXCH_CDE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券交易所代码' NOT NULL,
      CMSN_ABTM DECIMAL(6,5) TITLE '佣金扣减' NOT NULL DEFAULT 0.00000 ,
      DELT_CNDT CHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '剔除条件' NOT NULL DEFAULT '00000000',
      ABNO_INCM_CALC_TIME TIMESTAMP(0) TITLE '异常收益计算时间' NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      ABNO_INCM_CALC_TRM_USER VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算前端用户' NOT NULL,
      ABNO_INCM_CALC_BTCH_STS CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次状态' NOT NULL)
UNIQUE PRIMARY INDEX ( ABNO_INCM_CALC_BTCH );


CREATE MULTISET TABLE WXHDATA.ABNO_INCM_CALC_RESULT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_EXCH_CDE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券交易所代码' NOT NULL,
      SEC_ACCT CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券账户' NOT NULL,
      SEC_CDE CHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券代码' NOT NULL,
      OAP_ACCT_NBR CHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '一码通账户' NOT NULL,
      ACCT_NAME VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '账户名称' NOT NULL,
      CLSF_2 CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '投资者二级分类' NOT NULL,
      CLSF_3 CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '投资者三级分类' NOT NULL,
      IS_ODS CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '是否董监高' NOT NULL,
      IS_TOP10_SHDR CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '是否十大股东' NOT NULL,
      IS_LIFT_BAN_LMT_SHDR CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '是否解禁限售股东' NOT NULL,
      START_HLD_MKT_VAL DECIMAL(18,2) TITLE '期初持有市值' NOT NULL,
      END_HLD_MKT_VAL DECIMAL(18,2) TITLE '期末持有市值' NOT NULL,
      BUY_AMT DECIMAL(18,2) TITLE '买入金额' NOT NULL,
      SAL_AMT DECIMAL(18,2) TITLE '卖出金额' NOT NULL,
      NON_TRAD_TRAN_INCM_AMT DECIMAL(18,2) TITLE '非交易过户收入金额' NOT NULL,
      NON_TRAD_TRAN_EXPDT_AMT DECIMAL(18,2) TITLE '非交易过户支出金额' NOT NULL,
      SPRD_STOCK_ESTMT_AMT DECIMAL(18,2) TITLE '差额股份估算金额' NOT NULL,
      CASH_DVD DECIMAL(18,2) TITLE '现金分红' NOT NULL,
      TAX_FEE DECIMAL(18,2) TITLE '税费' NOT NULL,
      CMSN DECIMAL(18,2) TITLE '佣金' NOT NULL,
      BRKV_AMT DECIMAL(18,2) TITLE '盈亏金额' NOT NULL,
      ABNO_INCM_CALC_BTCH CHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次' NOT NULL)
PRIMARY INDEX ( SEC_ACCT );


CREATE MULTISET TABLE WXHDATA.MID_ABNO_INCM_CACL_DTL ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_EXCH_CDE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券交易所代码' NOT NULL,
      SEC_ACCT CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券账户' NOT NULL,
      SEC_CDE CHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券代码' NOT NULL,
      BIZ_TYPE CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '业务类型' NOT NULL,
      TAX_FEE DECIMAL(18,3) TITLE '税费' NOT NULL,
      BUY_VOL DECIMAL(18,0) TITLE '买入数量' NOT NULL,
      SAL_VOL DECIMAL(18,0) TITLE '卖出数量' NOT NULL,
      BUY_AMT DECIMAL(18,2) TITLE '买入金额' NOT NULL,
      SAL_AMT DECIMAL(18,2) TITLE '卖出金额' NOT NULL,
      ABNO_INCM_CALC_BTCH CHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '异常收益计算批次' NOT NULL)
PRIMARY INDEX ( SEC_ACCT );

