
-- 沪市清算交收明细表
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_CLR_STM_DTL ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      MKT_CDE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '市场代码' NOT NULL,
      RCOD_TYPE CHAR(5) CHARACTER SET LATIN CASESPECIFIC TITLE '记录类型' NOT NULL,
      BRGN_MODE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '交易方式' NOT NULL,
      SETL_MODE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '交收方式' NOT NULL,
      TRAD_NBR DECIMAL(18,0) TITLE '成交编号' NOT NULL,
      BIZ_SORT CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '业务类别' NOT NULL,
      CLR_INDC CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '清算标志' NOT NULL,
      TRANS_TYPE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '过户类型' NOT NULL,
      SETL_NBR VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC TITLE '交收编号' NOT NULL,
      APLY_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '申请编号' NOT NULL,
      CMT_NBR VARCHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '委托编号' NOT NULL,
      TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE '交易日期' NOT NULL,
      CLR_DATE DATE FORMAT 'YYYYMMDD' TITLE '清算日期' NOT NULL,
      SETL_DATE DATE FORMAT 'YYYYMMDD' TITLE '交收日期' NOT NULL,
      OTH_DATE DATE FORMAT 'YYYYMMDD' TITLE '其他日期' NOT NULL,
      CMT_TIME INTEGER TITLE '委托时间' NOT NULL,
      TRAD_TIME INTEGER TITLE '成交时间' NOT NULL,
      SEAT_CDE1 CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码1' NOT NULL,
      SEAT_CDE2 CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码2' NOT NULL,
      BRCH_CDE CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '营业部代码' NOT NULL,
      BLNGS_MEMB_CDE CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '所属会员代码' NOT NULL,
      SETL_MEMB CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '交收会员' NOT NULL,
      CSTD_MEMB CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '托管会员' NOT NULL,
      SEC_CDE1 INTEGER TITLE '证券代码1' NOT NULL,
      SEC_CDE2 INTEGER TITLE '证券代码2' NOT NULL,
      SEC_CTG CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '证券类别' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      EQUT_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '权益类型' NOT NULL,
      EQUT_YEARS SMALLINT TITLE '权益年份' NOT NULL,
      TRAD_DIRC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '成交方向' NOT NULL,
      SETL_VOL DECIMAL(18,0) TITLE '交收数量' NOT NULL,
      TRAD_VOL DECIMAL(18,0) TITLE '成交数量' NOT NULL,
      BANKRL_ACCT CHAR(25) CHARACTER SET LATIN CASESPECIFIC TITLE '资金账户' NOT NULL,
      CRNC_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '货币代码' NOT NULL,
      PRC1 DECIMAL(18,11) TITLE '价格1' NOT NULL,
      PRC2 DECIMAL(18,11) TITLE '价格2' NOT NULL,
      CLR_AMT DECIMAL(18,2) TITLE '清算金额' NOT NULL,
      STMP_TAX DECIMAL(18,3) TITLE '印花税' NOT NULL,
      HAND_FEE DECIMAL(18,3) TITLE '经手费' NOT NULL,
      TRAN_FEE DECIMAL(18,3) TITLE '过户费' NOT NULL,
      CMSN_CHG DECIMAL(18,2) TITLE '手续费' NOT NULL,
      ADMIN_CHRG DECIMAL(18,3) TITLE '证管费' NOT NULL,
      OTH_AMT1 DECIMAL(18,2) TITLE '其它金额1' NOT NULL,
      OTH_AMT2 DECIMAL(18,2) TITLE '其它金额2' NOT NULL,
      OTH_AMT3 DECIMAL(18,2) TITLE '其它金额3' NOT NULL,
      FACT_PAMT DECIMAL(18,2) TITLE '实际收付' NOT NULL,
      RESULT_CDE CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '结果代码' NOT NULL,
      SBJN_DSCR VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '附加说明' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT )
PARTITION BY ( RANGE_N(data_date  BETWEEN DATE '2004-01-01' AND DATE '2014-12-31' EACH INTERVAL '1' MONTH ,
DATE '2015-01-01' AND DATE '2100-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE),RANGE_N(clr_date  BETWEEN DATE '2004-01-01' AND DATE '2014-12-31' EACH INTERVAL '1' MONTH ,
DATE '2015-01-01' AND DATE '2100-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE),RANGE_N(trad_date  BETWEEN DATE '2004-01-01' AND DATE '2014-12-31' EACH INTERVAL '1' MONTH ,
DATE '2015-01-01' AND DATE '2100-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE) );

-- 沪市结算账户设置历史表 
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_STM_ACCT_SETUP_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      RSRV_ACCT CHAR(18) CHARACTER SET LATIN CASESPECIFIC TITLE '备付金账户' NOT NULL,
      ACCT_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '账户类别' NOT NULL,
      INDC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '标志' NOT NULL,
      SEC_SETL_ACCT CHAR(15) CHARACTER SET LATIN CASESPECIFIC TITLE '证券结算账户' NOT NULL,
      ALT_DATE DATE FORMAT 'YYYYMMDD' TITLE '修改日期' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( RSRV_ACCT );

-- 证券信息表
CREATE MULTISET TABLE nsODATA_D1.CSDC_INTG_SEC_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MKT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '市场类别' NOT NULL,
      SEC_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      SEC_NAME VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC TITLE '证券名称' NOT NULL,
      SEC_PAR_VAL DECIMAL(9,2) TITLE '证券面值' NOT NULL,
      ISS_DATE DATE FORMAT 'YYYYMMDD' TITLE '发行日期' NOT NULL,
      LIST_DATE DATE FORMAT 'YYYYMMDD' TITLE '上市日期' NOT NULL,
      MAT_DATE DATE FORMAT 'YYYYMMDD' TITLE '到期日期' NOT NULL,
      CRNC_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '币种代码' NOT NULL,
      SEC_UNIT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券单位类别' NOT NULL,
      SEC_REG_STS_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券登记状态类别' NOT NULL,
      MKT_LVL_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '市场层次类别' NOT NULL,
      SEC_CTG CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '证券类别' NOT NULL,
      ISSR_ID VARCHAR(12) CHARACTER SET LATIN CASESPECIFIC TITLE '发行人标识' NOT NULL,
      SRC_SEC_CTG CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '源证券类别' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( MKT_SORT ,SEC_CDE );

-- 沪市证券成交表
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_SEC_TRAD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      TRAD_NBR DECIMAL(18,0) TITLE '成交编号' NOT NULL,
      TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE '成交日期' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      BUY_DECL_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '买方申报编号' NOT NULL,
      B_SHR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '买方股东账户' NOT NULL,
      BUY_SEAT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '买方席位' NOT NULL,
      BUY_OPRTR_NBR CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '买方马甲编号' NOT NULL,
      BUY_DECL_TIME INTEGER TITLE '买方申报时间' NOT NULL,
      BUY_APLY_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '买方申请编号' NOT NULL,
      BUY_THIS_BAL DECIMAL(18,2) TITLE '买方本次余额' NOT NULL,
      SAL_DECL_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '卖方申报编号' NOT NULL,
      SAL_SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '卖方股东账户' NOT NULL,
      SAL_SEAT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '卖方席位' NOT NULL,
      SAL_OPRTR_NBR CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '卖方马甲编号' NOT NULL,
      SAL_DECL_TIME INTEGER TITLE '卖方申报时间' NOT NULL,
      SAL_APLY_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '卖方申请编号' NOT NULL,
      SAL_THIS_BAL DECIMAL(18,2) TITLE '卖方本次余额' NOT NULL,
      TRAD_TIME INTEGER TITLE '成交时间' NOT NULL,
      TRAN_PRC DECIMAL(18,6) TITLE '成交价格' NOT NULL,
      TRAD_VOL DECIMAL(18,0) TITLE '成交数量' NOT NULL,
      TRAD_INDC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '成交标志' NOT NULL,
      BRGN_MODE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '交易方式' NOT NULL,
      BIZ_TYPE CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '业务类型' NOT NULL,
      ASST_SEC_CDE INTEGER TITLE '辅助证券代码' NOT NULL,
      AMT DECIMAL(18,2) TITLE '金额' NOT NULL,
      RCOD_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '记录编号' NOT NULL,
      MEMO VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '备用' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( TRAD_NBR )
PARTITION BY RANGE_N(trad_date  BETWEEN DATE '0001-01-01' AND DATE '0001-01-02',
DATE '1900-01-01' AND DATE '2050-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);

-- 沪市非交易过户表 
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_NON_TRAD_TRAN ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      TRANS_DATE DATE FORMAT 'YYYYMMDD' TITLE '过户日期' NOT NULL,
      TRAD_NBR DECIMAL(18,0) TITLE '成交编号' NOT NULL,
      APLY_NBR CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '申请编号' NOT NULL,
      ORIG_SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '原席位代码' NOT NULL,
      ATA CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '过出账户' NOT NULL,
      OUT_SEAT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '过出席位' NOT NULL,
      IN_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '过入账户' NOT NULL,
      IN_SEAT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '过入席位' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      CAP_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股本类型' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      EQUT_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '权益类型' NOT NULL,
      EQUT_YEARS SMALLINT TITLE '权益年份' NOT NULL,
      TRANS_TYPE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '过户类型' NOT NULL,
      TRANS_VOL DECIMAL(18,0) TITLE '过户数量' NOT NULL,
      SRC_TRAN_PRC DECIMAL(18,6) TITLE '源成交价格' NOT NULL,
      TRAN_PRC DECIMAL(18,6) TITLE '成交价格' NOT NULL,
      TRAN_FEE DECIMAL(18,3) TITLE '过户费' NOT NULL,
      STMP_TAX DECIMAL(18,3) TITLE '印花税' NOT NULL,
      CMSN_CHG DECIMAL(18,2) TITLE '手续费' NOT NULL,
      ORG_CDE VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '机构代码' NOT NULL,
      TRANS_RESN CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '过户原因' NOT NULL,
      SUCC_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '成功标志' NOT NULL,
      RMAK_DESC VARCHAR(200) CHARACTER SET LATIN CASESPECIFIC TITLE '备注描述' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( TRANS_DATE ,ATA );

-- 沪深两市证券持有历史表
CREATE MULTISET TABLE nsPDATA_D1.ACT_SEC_HOLD_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MKT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '市场类别' NOT NULL,
      SEC_ACCT_NBR VARCHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户号' NOT NULL,
      CSTD_UNIT_ID CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '托管单元标识' NOT NULL,
      SEC_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      CAP_TYPE CHAR(5) CHARACTER SET LATIN CASESPECIFIC TITLE '股本类型' NOT NULL,
      TD_END_HOLD_VOL DECIMAL(18,0) TITLE '日终持有数量',
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期',
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期')
PRIMARY INDEX ( SEC_ACCT_NBR );

-- 沪市新股发行信息表
CREATE MULTISET TABLE nsPUBMart.MID_IPO_ISS_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      STK_CDE CHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '股票代码' NOT NULL,
      ISS_DATE DATE FORMAT 'YYYYMMDD' TITLE '发行日期',
      LIST_DATE DATE FORMAT 'YYYYMMDD' TITLE '上市日期',
      SEC_EXCH_CDE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券交易所代码',
      LSTN_BORD CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '上市板块',
      SEC_CTG CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券类别',
      CAP DECIMAL(24,6) TITLE '股本',
      ISS_PRC DECIMAL(24,6) TITLE '发行价格',
      FD_OPN_PRC DECIMAL(24,6) TITLE '首日开盘价',
      FD_CLS_PRC DECIMAL(24,6) TITLE '首日收盘价',
      OLN_ISS_LTRT DECIMAL(24,6) TITLE '网上发行中签率',
      ISS_PE DECIMAL(24,6) TITLE '发行市盈率',
      IPO_VOL DECIMAL(24,6) TITLE '首发数量',
      IPO_FUND_RSN_AMT DECIMAL(24,6) TITLE '首发筹资金额',
      FD_OPN_CHG_RATE DECIMAL(24,6) TITLE '首日开盘涨跌幅',
      FD_CLS_CHG_RATE DECIMAL(24,6) TITLE '首日收盘涨跌幅',
      FD_CHG_RATE DECIMAL(24,6) TITLE '首日涨跌幅',
      FD_TNOV_RATE DECIMAL(24,6) TITLE '首日换手率',
      IF_BREK CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '是否破发',
      CLCT_BANKRL_TOT DECIMAL(24,6) TITLE '募集资金合计',
      EST_CLCT_BANKRL DECIMAL(24,6) TITLE '预计募集资金',
      OSUB_RATE DECIMAL(24,6) TITLE '超募比率')
PRIMARY INDEX ( STK_CDE );

-- 股票增发信息表
CREATE MULTISET TABLE nsODATA_D1.SSE_STK_FI_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EXCH CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '交易所' NOT NULL,
      STK_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '股票代码' NOT NULL,
      STK_ABBR CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '股票简称' NOT NULL,
      ISSR_NAME VARCHAR(200) CHARACTER SET LATIN CASESPECIFIC TITLE '发行人名称' NOT NULL,
      ISS_DATE DATE FORMAT 'YYYYMMDD' TITLE '发行日期' NOT NULL,
      FI_BLTN_D DATE FORMAT 'YYYYMMDD' TITLE '增发公告日' NOT NULL,
      FI_LIST_DATE DATE FORMAT 'YYYYMMDD' TITLE '增发上市日期' NOT NULL,
      FI_MODE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '增发方式' NOT NULL,
      SUBSC_MODE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '认购方式' NOT NULL,
      CLCT_BANKRL_TOT_AMT DECIMAL(18,2) TITLE '募集资金总额' NOT NULL,
      CLCT_CASH_TOT_AMT DECIMAL(18,2) TITLE '募集现金总额' NOT NULL,
      ISS_TOT_CHRG DECIMAL(18,2) TITLE '发行总费用' NOT NULL,
      CLCT_BANKRL_NET_AMT DECIMAL(18,2) TITLE '募集资金净额' NOT NULL,
      ISS_PRC DECIMAL(18,5) TITLE '发行价格' NOT NULL,
      ISS_VOL DECIMAL(18,0) TITLE '发行数量' NOT NULL,
      FI_AGO_TCAP DECIMAL(18,0) TITLE '增发前总股本' NOT NULL,
      CONSG VARCHAR(120) CHARACTER SET LATIN CASESPECIFIC TITLE '主承销商' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( STK_CDE );

-- 沪市证券及指数行情表
CREATE MULTISET TABLE nsODATA_D1.SSE_SEC_IDX_QUOT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_CDE VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      SEC_NAME VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证券名称' NOT NULL,
      AGO_CLS_PRC DECIMAL(8,3) TITLE '前收盘价格' NOT NULL,
      TS_OPN_PRC DECIMAL(8,3) TITLE '今开盘价格' NOT NULL,
      TS_TRAD_AMT DECIMAL(12,0) TITLE '今成交金额' NOT NULL,
      TOP_PRC DECIMAL(8,3) TITLE '最高价格' NOT NULL,
      MIN_PRC DECIMAL(8,3) TITLE '最低价格' NOT NULL,
      LTST_PRC DECIMAL(8,3) TITLE '最新价格' NOT NULL,
      TRAD_VOL DECIMAL(10,0) TITLE '成交数量' NOT NULL,
      CRENT_BUY_PRC DECIMAL(8,3) TITLE '当前买入价格' NOT NULL,
      CRENT_SAL_PRC DECIMAL(8,3) TITLE '当前卖出价格' NOT NULL,
      PE DECIMAL(8,3) TITLE '市盈率',
      APPBY_QTT_ONE DECIMAL(10,0) TITLE '申买量一' NOT NULL,
      APPBY_PRC_TWO DECIMAL(8,3) TITLE '申买价二' NOT NULL,
      APPBY_QTT_TWO DECIMAL(10,0) TITLE '申买量二' NOT NULL,
      APPBY_PRC_THREE DECIMAL(8,3) TITLE '申买价三' NOT NULL,
      APPBY_QTT_THREE DECIMAL(10,0) TITLE '申买量三' NOT NULL,
      APPSL_QTT_ONE DECIMAL(10,0) TITLE '申卖量一' NOT NULL,
      APPSL_PRC_TWO DECIMAL(8,3) TITLE '申卖价二' NOT NULL,
      APPSL_QTT_TWO DECIMAL(10,0) TITLE '申卖量二' NOT NULL,
      APPSL_PRC_THREE DECIMAL(8,3) TITLE '申卖价三' NOT NULL,
      APPSL_QTT_THREE DECIMAL(10,0) TITLE '申卖量三' NOT NULL,
      APPBY_PRC_FR DECIMAL(8,3) TITLE '申买价四',
      APPBY_QTT_FR DECIMAL(10,0) TITLE '申买量四',
      APPBY_PRC_FV DECIMAL(8,3) TITLE '申买价五',
      APPBY_QTT_FV DECIMAL(10,0) TITLE '申买量五',
      APPSL_PRC_FR DECIMAL(8,3) TITLE '申卖价四',
      APPSL_QTT_FR DECIMAL(10,0) TITLE '申卖量四',
      APPSL_PRC_FV DECIMAL(8,3) TITLE '申卖价五',
      APPSL_QTT_FV DECIMAL(10,0) TITLE '申卖量五',
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SEC_CDE );

-- 沪市权益登记表
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_EQT_REG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      REG_NBR DECIMAL(9,0) TITLE '登记序号' NOT NULL,
      REG_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '登记类别' NOT NULL,
      CSTD_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '托管类别' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      LIST_CDE INTEGER TITLE '上市代码' NOT NULL,
      ISS_CDE INTEGER TITLE '发行代码' NOT NULL,
      CAP_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股本类型' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      EQUT_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '权益类型' NOT NULL,
      EQUT_YEARS SMALLINT TITLE '权益年份' NOT NULL,
      EQUT_ORDER SMALLINT TITLE '权益顺序' NOT NULL,
      REG_DATE DATE FORMAT 'YYYYMMDD' TITLE '登记日期' NOT NULL,
      EXR_DATE DATE FORMAT 'YYYYMMDD' TITLE '除权日期' NOT NULL,
      LSTD_DATE DATE FORMAT 'YYYYMMDD' TITLE '挂牌日期' NOT NULL,
      DLST_DATE DATE FORMAT 'YYYYMMDD' TITLE '摘牌日期' NOT NULL,
      LIST_DATE DATE FORMAT 'YYYYMMDD' TITLE '上市日期' NOT NULL,
      BLTN_DATE DATE FORMAT 'YYYYMMDD' TITLE '公告日期' NOT NULL,
      RIGHT_PRC DECIMAL(12,5) TITLE '配股价格' NOT NULL,
      BEF_TAX_DIVD DECIMAL(18,6) TITLE '税前红利' NOT NULL,
      AFT_TAX_DIVD DECIMAL(18,6) TITLE '税后红利' NOT NULL,
      ASGN_RIGHT_CHRG DECIMAL(9,3) TITLE '转配费用' NOT NULL,
      CAP_VOL DECIMAL(18,0) TITLE '股本数量' NOT NULL,
      REG_VOL DECIMAL(18,0) TITLE '登记数量' NOT NULL,
      ALLOT_DENOM DECIMAL(18,6) TITLE '配比分母' NOT NULL,
      ALLOT_NUMRT DECIMAL(18,6) TITLE '配比分子' NOT NULL,
      TRSC_FEE_RATE DECIMAL(9,7) TITLE '交易费率' NOT NULL,
      RATE680 DECIMAL(9,7) TITLE '费率680' NOT NULL,
      MKUP_RATE DECIMAL(9,7) TITLE '补领费率' NOT NULL,
      MKUP_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '补领标志' NOT NULL,
      EQUT_ABBR VARCHAR(40) CHARACTER SET LATIN CASESPECIFIC TITLE '权益简称' NOT NULL,
      AREA_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '地区代码' NOT NULL,
      CNSG_MODE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '承销方式' NOT NULL,
      CONSG VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '主承销商' NOT NULL,
      CNSG_SEAT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '承销席位' NOT NULL,
      CNSG_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '承销账户' NOT NULL,
      CNSG_TEL VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '承销电话' NOT NULL,
      EQL_RIGHT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '同股同权' NOT NULL,
      EXCT_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '执行标志' NOT NULL,
      LSTD_CHK_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '挂牌复核标志' NOT NULL,
      ALT_DATE DATE FORMAT 'YYYYMMDD' TITLE '修改日期' NOT NULL,
      RMAK_DESC VARCHAR(200) CHARACTER SET LATIN CASESPECIFIC TITLE '备注描述' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( REG_NBR );


---------------------------------------------------------------------------------------------------

-- 深市清算过户成交表
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_CLR_TRANS_TRAD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE '成交日期' NOT NULL,
      SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码' NOT NULL,
      SRC_BUY_VOL DECIMAL(18,0) TITLE '源买入数量' NOT NULL,
      BUY_VOL DECIMAL(18,0) TITLE '买入数量' NOT NULL,
      BUY_AMT DECIMAL(18,3) TITLE '买入金额' NOT NULL,
      SRC_SAL_VOL DECIMAL(18,0) TITLE '源卖出数量' NOT NULL,
      SAL_VOL DECIMAL(18,0) TITLE '卖出数量' NOT NULL,
      SAL_AMT DECIMAL(18,3) TITLE '卖出金额' NOT NULL,
      BUY_HAND_FEE DECIMAL(18,2) TITLE '买方经手费' NOT NULL,
      SAL_HAND_FEE DECIMAL(18,2) TITLE '卖方经手费' NOT NULL,
      BUY_STMP_TAX DECIMAL(18,2) TITLE '买方印花税' NOT NULL,
      SAL_STMP_TAX DECIMAL(18,2) TITLE '卖方印花税' NOT NULL,
      BUY_TRAN_FEE DECIMAL(18,2) TITLE '买方过户费' NOT NULL,
      SAL_TRAN_FEE DECIMAL(18,2) TITLE '卖方过户费' NOT NULL,
      BUY_CMSN_CHG DECIMAL(18,2) TITLE '买方手续费' NOT NULL,
      SAL_CMSN_CHG DECIMAL(18,2) TITLE '卖方手续费' NOT NULL,
      PRCS_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '处理标志' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT );

-- 深市 信用交易席位账户关系历史
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_CRDT_TRAD_SEAT_ACCT_RLTN_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_LN_BROKER_ACCT CHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '融券券商账户' NOT NULL,
      CSTD_UNIT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '托管单元' NOT NULL,
      CRDT_SUM_ACCT CHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '信用汇总账户' NOT NULL,
      TYPE_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '类型标志' NOT NULL,
      VLD_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '有效标志' NOT NULL,
      MEMO_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志' NOT NULL,
      MEMO_FLD CHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '备用字段' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( SEC_LN_BROKER_ACCT );

-- 深市 股东持有变动表（2017-04-30日前有效）
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_SHDR_HLD_CHG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CHG_DATE DATE FORMAT 'YYYYMMDD' TITLE '变更日期' NOT NULL,
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码' NOT NULL,
      STK_CHRC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股份性质' NOT NULL,
      CHG_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '变更代码' NOT NULL,
      SRC_BEF_CHG_HOLD_VOL DECIMAL(18,0) TITLE '源变更前持有数量' NOT NULL,
      BEF_CHG_HOLD_VOL DECIMAL(18,0) TITLE '变更前持有数量' NOT NULL,
      SRC_CHG_VOL DECIMAL(18,0) TITLE '源变更数量' NOT NULL,
      CHG_VOL DECIMAL(18,0) TITLE '变更数量' NOT NULL,
      PRCS_DATE DATE FORMAT 'YYYYMMDD' TITLE '处理日期' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT );

-- 深市 股份变更表（2017-05-01日后有效）
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_STK_CHG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SHDR_ACCT VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      SEC_CDE VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      STK_CHRC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股份性质' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      CSTD_UNIT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '托管单元' NOT NULL,
      SRC_BEF_CHG_HOLD_VOL DECIMAL(17,2) TITLE '源变更前持有数量' NOT NULL,
      BEF_CHG_HOLD_VOL DECIMAL(17,2) TITLE '变更前持有数量' NOT NULL,
      SRC_CHG_VOL DECIMAL(17,2) TITLE '源变更数量' NOT NULL,
      CHG_VOL DECIMAL(17,2) TITLE '变更数量' NOT NULL,
      INSTR_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '指令序号' NOT NULL,
      CHG_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '变更代号' NOT NULL,
      CHG_DATE DATE FORMAT 'YYYYMMDD' TITLE '变更日期' NOT NULL,
      CHG_TIME VARCHAR(26) CHARACTER SET LATIN CASESPECIFIC TITLE '变更时间' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT );

-- 深市 股票增发信息
CREATE MULTISET TABLE nsODATA.SZSE_STK_FI_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EXCH CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '交易所' NOT NULL,
      STK_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '股票代码' NOT NULL,
      STK_ABBR VARCHAR(24) CHARACTER SET LATIN CASESPECIFIC TITLE '股票简称' NOT NULL,
      ISSR_NAME VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '发行人名称' NOT NULL,
      ISS_DATE DATE FORMAT 'YYYYMMDD' TITLE '发行日期' NOT NULL,
      FI_BLTN_D DATE FORMAT 'YYYYMMDD' TITLE '增发公告日' NOT NULL,
      FI_LIST_DATE DATE FORMAT 'YYYYMMDD' TITLE '增发上市日期' NOT NULL,
      FI_MODE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '增发方式' NOT NULL,
      SUBSC_MODE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '认购方式' NOT NULL,
      ORTN_FI_AIM VARCHAR(255) CHARACTER SET LATIN CASESPECIFIC TITLE '定向增发目的' NOT NULL,
      EST_CLCT_FUND DECIMAL(19,3) TITLE '预计募集资金' NOT NULL,
      EST_CLCT_CASH_TOT_AMT DECIMAL(19,3) TITLE '预计募集现金总额' NOT NULL,
      CLCT_FUND_TOT_AMT DECIMAL(19,3) TITLE '募集资金总额' NOT NULL,
      CLCT_CASH_TOT_AMT DECIMAL(19,3) TITLE '募集现金总额' NOT NULL,
      ISS_TOT_CHRG DECIMAL(19,3) TITLE '发行总费用' NOT NULL,
      CLCT_FUND_NET_AMT DECIMAL(19,3) TITLE '募集资金净额' NOT NULL,
      ISS_PRC DECIMAL(9,3) TITLE '发行价格' NOT NULL,
      ISS_VOL DECIMAL(13,0) TITLE '发行数量' NOT NULL,
      FI_AGO_TCAP DECIMAL(13,0) TITLE '增发前总股本' NOT NULL,
      CONSG_CDE CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '主承销商代码' NOT NULL,
      CONSG_NAME VARCHAR(255) CHARACTER SET LATIN CASESPECIFIC TITLE '主承销商名称' NOT NULL,
      FI_TDHL_D DATE FORMAT 'YYYYMMDD' TITLE '增发停牌日' NOT NULL,
      FI_ROT_D DATE FORMAT 'YYYYMMDD' TITLE '增发复牌日' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( STK_CDE );

-- 深市 配股参数历史表
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_RIGHT_PRMT_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EQUT_BIZ_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '权益业务编号' NOT NULL,
      BIZ_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '业务编号' NOT NULL,
      right_warnt_code CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '配股权证代码' NOT NULL,
      SUBSC_PRC DECIMAL(13,4) TITLE '认购价格' NOT NULL,
      SUBSC_B_DATE DATE FORMAT 'YYYYMMDD' TITLE '认购起始日期' NOT NULL,
      SUBSC_CUT_OFF_DATE DATE FORMAT 'YYYYMMDD' TITLE '认购截止日期' NOT NULL,
      CONV_SEC_CDE CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '转换证券代码' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      RIGHT_ARRV_DATE DATE FORMAT 'YYYYMMDD' TITLE '配股到账日期' NOT NULL,
      CONV_RATE_NUMRT DECIMAL(8,4) TITLE '转换比例分子' NOT NULL,
      CONV_RATE_DENOM DECIMAL(8,4) TITLE '转换比例分母' NOT NULL,
      CONSG_CLR_ACCT CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '主承销商结算账号' NOT NULL,
      RIGHT_YEARLY DECIMAL(4,0) TITLE '配股年度' NOT NULL,
      RIGHT_CNT DECIMAL(2,0) TITLE '配股次数' NOT NULL,
      PRCS_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '处理标志' NOT NULL,
      MEMO_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( EQUT_BIZ_NBR );

-- 深市 公司红利参数历史表
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_COMP_ACT_DIVD_PRMT_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      BIZ_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '业务编号' NOT NULL,
      BIZ_SUB_NBR DECIMAL(9,0) TITLE '业务子序号' NOT NULL,
      EQUT_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '权益类别' NOT NULL,
      STK_CHRC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股份性质' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      BLTN_CRNC CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '公告币种' NOT NULL,
      DISTR_CRNC CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '派发币种' NOT NULL,
      BEF_TAX_RATE_NUMRT DECIMAL(25,10) TITLE '税前比例分子' NOT NULL,
      BEF_TAX_RATE_DENOM DECIMAL(25,10) TITLE '税前比例分母' NOT NULL,
      IF_CNTN_OPT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '是否含选择权' NOT NULL,
      bw_list_id CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '黑白名单标识' NOT NULL,
      STP_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '自派标志' NOT NULL,
      CHRG_MODE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '收费方式' NOT NULL,
      CLR_DATE DATE FORMAT 'YYYYMMDD' TITLE '清算日期' NOT NULL,
      ARRV_DATE DATE FORMAT 'YYYYMMDD' TITLE '到账日期' NOT NULL,
      FRAG_MODE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '零碎方式' NOT NULL,
      PRCS_STS CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '处理状态' NOT NULL,
      MEMO_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志' NOT NULL,
      MEMO_DATE DATE FORMAT 'YYYYMMDD' TITLE '备用日期' NOT NULL,
      MEMO_NBR DECIMAL(17,2) TITLE '备用数字' NOT NULL,
      MEMO_FLD CHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '备用字段' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( BIZ_NBR );

-- 深市 公司权益参数历史表
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_COMP_ACT_EQUT_PRMT_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_CDE VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      BIZ_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '业务编号' NOT NULL,
      EQUT_NBR CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '权益编号' NOT NULL,
      EQUITY_REG_DATE DATE FORMAT 'YYYYMMDD' TITLE '股权登记日期' NOT NULL,
      B_SHR_LAST_TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE 'B股最后交易日期' NOT NULL,
      EQUT_YEARLY DECIMAL(4,0) TITLE '权益年度' NOT NULL,
      EQUT_CNT DECIMAL(2,0) TITLE '权益次数' NOT NULL,
      B_SHR_JV_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE 'B股合资标志' NOT NULL,
      EXCH_RT DECIMAL(18,10) TITLE '汇率' NOT NULL,
      MEMO_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志' NOT NULL,
      MEMO_DATE DATE FORMAT 'YYYYMMDD' TITLE '备用日期' NOT NULL,
      MEMO_NBR DECIMAL(17,2) TITLE '备用数字' NOT NULL,
      MEMO_FLD CHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '备用字段' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( SEC_CDE );

-- 深市 可转债交易表
CREATE MULTISET TABLE nsODATA.CSDC_S_CONV_BOND_TRAD ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CONV_BOND_CDE INTEGER TITLE '可转债代码' NOT NULL,
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      PRCS_DATE DATE FORMAT 'YYYYMMDD' TITLE '处理日期' NOT NULL,
      SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码' NOT NULL,
      SRC_CMT_VOL DECIMAL(18,0) TITLE '源委托数量' NOT NULL,
      CMT_VOL DECIMAL(18,0) TITLE '委托数量' NOT NULL,
      SRC_CFRM_VOL DECIMAL(18,0) TITLE '源确认数量' NOT NULL,
      CFRM_VOL DECIMAL(18,0) TITLE '确认数量' NOT NULL,
      CONV_VOL DECIMAL(18,0) TITLE '转股数量' NOT NULL,
      FRZ_VOL DECIMAL(18,2) TITLE '冻结数量' NOT NULL,
      BANKRL_AMT DECIMAL(18,2) TITLE '资金金额' NOT NULL,
      FRZ_AMT DECIMAL(18,2) TITLE '冻结金额' NOT NULL,
      BIZ_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '业务类别' NOT NULL,
      PRCS_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '处理标志' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT );

-- 深市 可转债登记表
CREATE MULTISET TABLE nsODATA.CSDC_S_CONV_BOND_REG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CONV_BOND_CDE INTEGER TITLE '可转债代码' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      SEC_PAR_VAL DECIMAL(9,2) TITLE '证券面值' NOT NULL,
      CONV_PRC DECIMAL(6,2) TITLE '转股价格' NOT NULL,
      CONV_S_DATE DATE FORMAT 'YYYYMMDD' TITLE '转股开始日期' NOT NULL,
      CONV_E_DATE DATE FORMAT 'YYYYMMDD' TITLE '转股结束日期' NOT NULL,
      SALBAK_PRC DECIMAL(6,2) TITLE '回售价格' NOT NULL,
      SALBAK_S_DATE DATE FORMAT 'YYYYMMDD' TITLE '回售开始日期' NOT NULL,
      SALBAK_E_DATE DATE FORMAT 'YYYYMMDD' TITLE '回售结束日期' NOT NULL,
      RE_IMBRS_INTR DECIMAL(18,5) TITLE '兑付利息' NOT NULL,
      TRAD_UNIT INTEGER TITLE '交易单位' NOT NULL,
      CONV_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '转股标志' NOT NULL,
      SALBAK_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '回售标志' NOT NULL,
      OPRTR_CDE CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '操作员代码' NOT NULL,
      PRCS_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '处理标志' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( CONV_BOND_CDE );


-- 深市 明细结果表
CREATE MULTISET TABLE nsODATA_D1.CSDC_S_DTL_RESULT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SHDR_ACCT VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      CLR_ACCT VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '结算账号' NOT NULL,
      RSRV_ACCT VARCHAR(25) CHARACTER SET LATIN CASESPECIFIC TITLE '备付金账户' NOT NULL,
      DATA_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '数据类型' NOT NULL,
      BIZ_SORT CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '业务类别' NOT NULL,
      SEC_CDE VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码' NOT NULL,
      TRAD_UNIT VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '交易单元' NOT NULL,
      CSTD_UNIT VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '托管单元' NOT NULL,
      CUST_ODR_NBR VARCHAR(24) CHARACTER SET LATIN CASESPECIFIC TITLE '客户订单编号' NOT NULL,
      BRCH_CDE CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '营业部代码' NOT NULL,
      EXCT_NBR VARCHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '执行编号' NOT NULL,
      BIZ_SEQ_NBR VARCHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '业务流水编号' NOT NULL,
      TRAD_VOL DECIMAL(30,2) TITLE '成交数量' NOT NULL,
      CLR_VOL DECIMAL(30,2) TITLE '清算数量' NOT NULL,
      SETL_VOL DECIMAL(30,2) TITLE '交收数量' NOT NULL,
      TRAN_PRC DECIMAL(30,4) TITLE '成交价格' NOT NULL,
      CLR_PRC DECIMAL(30,9) TITLE '清算价格' NOT NULL,
      CRDT_TRAD_ID CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '信用交易标识' NOT NULL,
      LQD_ID CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '平仓标识' NOT NULL,
      SEC_CTG CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '证券类别' NOT NULL,
      SEC_SUB_CLASS CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '证券子类' NOT NULL,
      STK_CHRC CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股份性质' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      SETL_MODE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '交收方式' NOT NULL,
      CRNC_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '货币代码' NOT NULL,
      CLR_CPS DECIMAL(30,2) TITLE '清算本金' NOT NULL,
      STMP_TAX DECIMAL(30,2) TITLE '印花税' NOT NULL,
      TRAD_HAND_FEE DECIMAL(30,2) TITLE '交易经手费' NOT NULL,
      SPVS_FEE DECIMAL(30,2) TITLE '监管规费' NOT NULL,
      TRAN_FEE DECIMAL(30,2) TITLE '过户费' NOT NULL,
      SETL_FEE DECIMAL(30,2) TITLE '结算费' NOT NULL,
      CMSN_CHG DECIMAL(30,2) TITLE '手续费' NOT NULL,
      BROKER_CMSN DECIMAL(30,2) TITLE '券商佣金' NOT NULL,
      OTH_CHRG DECIMAL(30,2) TITLE '其它费用' NOT NULL,
      BANKRL_AMT DECIMAL(30,2) TITLE '资金金额' NOT NULL,
      PAMT_NET_AMT DECIMAL(30,2) TITLE '收付净额' NOT NULL,
      SETL_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '交收标志' NOT NULL,
      SUMR_CDE CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '摘要代号' NOT NULL,
      TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE '成交日期' NOT NULL,
      CLR_DATE DATE FORMAT 'YYYYMMDD' TITLE '清算日期' NOT NULL,
      SETL_DATE DATE FORMAT 'YYYYMMDD' TITLE '交收日期' NOT NULL,
      SEND_DATE DATE FORMAT 'YYYYMMDD' TITLE '发送日期' NOT NULL,
      OTH_DATE DATE FORMAT 'YYYYMMDD' TITLE '其它日期' NOT NULL,
      MKT_CDE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '市场代码' NOT NULL,
      BRGN_MODE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '交易方式' NOT NULL,
      SEC_CDE2 VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证券代码2' NOT NULL,
      CSTD_UNIT2 VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '托管单元2' NOT NULL,
      ODR_NBR2 VARCHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '订单编号2' NOT NULL,
      SBJN_DSCR VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '附加说明' NOT NULL,
      MEMO_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( SHDR_ACCT ,SEC_CDE ,CUST_ODR_NBR );

-- 证券类别代码 （A股：11）
CREATE MULTISET TABLE CMSSDATA.CDE_SEC_SORT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_SORT_CDE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券类别代码' NOT NULL,
      SEC_SORT_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券类别名称' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '生效日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '失效日期' NOT NULL)
PRIMARY INDEX ( SEC_SORT_CDE );

-- 证券市场层次类别代码表（主板：1，中小板：2，创业板：3）
CREATE MULTISET TABLE CMSSDATA.CDE_SEC_MKT_LVL_SORT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_MKT_LVL_SORT_CDE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券市场层次类别代码' NOT NULL,
      SEC_MKT_LVL_SORT_NAME VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE '证券市场层次类别名称' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '生效日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '失效日期' NOT NULL)
PRIMARY INDEX ( SEC_MKT_LVL_SORT_CDE );


-- 账户分类历史
CREATE MULTISET TABLE nsPDATA_D1.ACT_STK_INVST_CLSF_HIS ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      OAP_ACCT_NBR VARCHAR(25) CHARACTER SET LATIN CASESPECIFIC TITLE '一码通账户号码',
      SEC_ACCT_NBR VARCHAR(25) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户号' NOT NULL,
      SEC_ACCT_NAME VARCHAR(120) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户名称',
      MKT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '市场类别',
      SEC_ACCT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户类别',
      CLSF_1 CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '一级分类',
      CLSF_2 CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '二级分类',
      CLSF_3 CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '三级分类',
      CMSMC_CLSF CHAR(4) CHARACTER SET LATIN CASESPECIFIC TITLE '中证监测分类',
      CLSF_2_AGE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '二级分类（年龄）',
      CLSF_3_AGE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '三级分类（年龄）',
      BNK_ID CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '银行标识',
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期',
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期')
PRIMARY INDEX ( SEC_ACCT_NBR );

-- 整合证券账户表
CREATE MULTISET TABLE nsODATA_D1.CSDC_INTG_SEC_ACCT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEC_ACCT VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户' NOT NULL,
      SEC_ACCT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户类别' NOT NULL,
      SEC_ACCT_USE_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户用途类别' NOT NULL,
      SEC_ACCT_STS CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户状态' NOT NULL,
      MKT_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '市场类别' NOT NULL,
      OPN_ACCT_DATE DATE FORMAT 'YYYYMMDD' TITLE '开户日期' NOT NULL,
      CLS_ACCT_DATE DATE FORMAT 'YYYYMMDD' TITLE '销户日期' NOT NULL,
      COUN_CDE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '国家代码' NOT NULL,
      OPN_ACCT_AREA_CDE VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '开户地区代码' NOT NULL,
      OPN_ACCT_AGT_ID CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '开户代理机构标识' NOT NULL,
      OPN_ACCT_AGT_NET_ID VARCHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '开户代理网点标识' NOT NULL,
      SEC_ACCT_NAME VARCHAR(128) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户名称' NOT NULL,
      SEC_ACCT_ABBR VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户简称' NOT NULL,
      SEC_ACCT_ENG_NAME VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户英文名称' NOT NULL,
      CERT_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '证件类别' NOT NULL,
      CERT_NBR VARCHAR(40) CHARACTER SET LATIN CASESPECIFIC TITLE '证件号码' NOT NULL,
      ORIG_CERT_NBR VARCHAR(40) CHARACTER SET LATIN CASESPECIFIC TITLE '原证件号码' NOT NULL,
      CERT_VLD_DATE VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '证件有效期' NOT NULL,
      DOM_ABR_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '境内外标志' NOT NULL,
      ORG_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '机构标志' NOT NULL,
      COMM_ADDR VARCHAR(160) CHARACTER SET LATIN CASESPECIFIC TITLE '通信地址' NOT NULL,
      PSTL_CDE VARCHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '邮政编码' NOT NULL,
      CNTC_TEL VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '联系电话' NOT NULL,
      MOB_NBR VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '手机号码' NOT NULL,
      FAX VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '传真' NOT NULL,
      EMAIL_ADDR VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '电子邮件地址' NOT NULL,
      HOMEPG VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '主页地址' NOT NULL,
      BORN_DATE DATE FORMAT 'YYYYMMDD' TITLE '出生日期' NOT NULL,
      GND CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '性别' NOT NULL,
      OCCU_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '职业类别' NOT NULL,
      EDU_LVL CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '教育程度' NOT NULL,
      ORG_CDE VARCHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '组织机构代码' NOT NULL,
      ORG_CDE_VLD_DATE VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '组织机构代码有效期' NOT NULL,
      CORP_REP VARCHAR(60) CHARACTER SET LATIN CASESPECIFIC TITLE '法人代表' NOT NULL,
      CORP_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '法人类别' NOT NULL,
      ENTRP_CHRC_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '企业性质类别' NOT NULL,
      STAT_OWN_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '国有标志' NOT NULL,
      SEC_ACCT_FRZ_STS_SORT CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '证券账户冻结状态类别' NOT NULL,
      TA_SYS_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE 'TA系统标志' NOT NULL,
      OPEN_FUND_ACCT_ASGN_INDC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '开放式基金账户配号标志' NOT NULL,
      INVST_SORT CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '投资者类别' NOT NULL,
      OAP_ACCT_NBR CHAR(25) CHARACTER SET LATIN CASESPECIFIC TITLE '一码通账户号码' NOT NULL,
      SRC_SEC_ACCT_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '源证券账户类别' NOT NULL,
      SRC_CUST_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '源客户类别' NOT NULL,
      SRC_ORG_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '源机构类别' NOT NULL,
      SRC_PROD_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '源产品类别' NOT NULL,
      SRC_SEC_ACCT_STS CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '源证券账户状态' NOT NULL,
      SPCL_SEC_ACCT_NAME VARCHAR(128) CHARACTER SET LATIN CASESPECIFIC TITLE '特殊证券账户名称' NOT NULL,
      OPN_ACCT_MODE_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '开户方式类别' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( SEC_ACCT );

-- 沪市证券过户表
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_SEC_TRAN ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      TRAD_DATE DATE FORMAT 'YYYYMMDD' TITLE '成交日期' NOT NULL,
      TRAD_NBR DECIMAL(18,0) TITLE '成交编号' NOT NULL,
      TRAD_DIRC CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '成交方向' NOT NULL,
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      SHDR_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '股东类型' NOT NULL,
      MST_SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '主席位代码' NOT NULL,
      SEAT_CDE CHAR(6) CHARACTER SET LATIN CASESPECIFIC TITLE '席位代码' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      CAP_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '股本类型' NOT NULL,
      NEGT_TYPE CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '流通类型' NOT NULL,
      EQUT_TYPE CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '权益类型' NOT NULL,
      EQUT_YEARS SMALLINT TITLE '权益年份' NOT NULL,
      TRANS_TYPE CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '过户类型' NOT NULL,
      TRANS_DATE DATE FORMAT 'YYYYMMDD' TITLE '过户日期' NOT NULL,
      TRANS_VOL DECIMAL(18,0) TITLE '过户数量' NOT NULL,
      THIS_BAL DECIMAL(18,0) TITLE '本次余额' NOT NULL,
      SRC_TRAN_PRC DECIMAL(18,6) TITLE '源成交价格' NOT NULL,
      TRAN_PRC DECIMAL(18,6) TITLE '成交价格' NOT NULL,
      TRAD_TIME INTEGER TITLE '成交时间' NOT NULL,
      APLY_NBR CHAR(16) CHARACTER SET LATIN CASESPECIFIC TITLE '申请编号' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( TRAD_DATE ,SHDR_ACCT )
PARTITION BY RANGE_N(trad_date  BETWEEN DATE '1991-07-08' AND DATE '2014-12-31' EACH INTERVAL '1' MONTH ,
DATE '2015-01-01' AND DATE '2100-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);

-- 沪市董监高交易限制情况表
CREATE MULTISET TABLE nsODATA_D1.CSDC_H_DSE_TRAD_LMT_CNDT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRCS_DATE DATE FORMAT 'YYYYMMDD' TITLE '处理日期' NOT NULL,
      SHDR_ACCT CHAR(10) CHARACTER SET LATIN CASESPECIFIC TITLE '股东账户' NOT NULL,
      SEC_CDE INTEGER TITLE '证券代码' NOT NULL,
      YDY_HOLD_VOL DECIMAL(18,0) TITLE '昨日持有数量' NOT NULL,
      YDY_NEGT_VOL DECIMAL(18,0) TITLE '昨日流通数量' NOT NULL,
      LMT_RATE INTEGER TITLE '限售比例' NOT NULL,
      INTD_LMT_LMT DECIMAL(18,0) TITLE '当日限售额度' NOT NULL,
      INTD_FACT_FRZ_VOL DECIMAL(18,0) TITLE '当日实际冻结数量' NOT NULL,
      SYS_SRC CHAR(3) CHARACTER SET LATIN CASESPECIFIC TITLE '系统来源' NOT NULL,
      MEMO_INDC1 CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '备用标志1' NOT NULL,
      RMAK_FLD VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '备注字段' NOT NULL,
      DATA_DATE DATE FORMAT 'YYYYMMDD' TITLE '数据日期' NOT NULL)
PRIMARY INDEX ( PRCS_DATE ,SHDR_ACCT );

-- 深市上市公司高管信息
CREATE MULTISET TABLE nsODATA_D1.SZSE_LC_EXCUT_INFO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Id VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC TITLE 'ID' NOT NULL,
      EXCH CHAR(1) CHARACTER SET LATIN CASESPECIFIC TITLE '交易所' NOT NULL,
      COMP_CDE CHAR(8) CHARACTER SET LATIN CASESPECIFIC TITLE '公司代码' NOT NULL,
      COMP_ABBR VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC TITLE '公司简称' NOT NULL,
      ORG_CDE VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC TITLE '组织机构代码' NOT NULL,
      EMPL_NAME VARCHAR(150) CHARACTER SET LATIN CASESPECIFIC TITLE '员工姓名' NOT NULL,
      IOT_DATE VARCHAR(400) CHARACTER SET LATIN CASESPECIFIC TITLE '上任日期' NOT NULL,
      OTG_DATE VARCHAR(400) CHARACTER SET LATIN CASESPECIFIC TITLE '离任日期' NOT NULL,
      CERT_SORT VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC TITLE '证件类别' NOT NULL,
      CERT_NBR VARCHAR(64) CHARACTER SET LATIN CASESPECIFIC TITLE '证件号码' NOT NULL,
      OFFHDG_TYPE VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC TITLE '任职类型' NOT NULL,
      NTLT VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC TITLE '国籍' NOT NULL,
      DUTY_TYPE VARCHAR(400) CHARACTER SET LATIN CASESPECIFIC TITLE '职务类型' NOT NULL,
      OFFHDG_STS VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC TITLE '任职状态' NOT NULL,
      GND CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '性别' NOT NULL,
      RSUM VARCHAR(8000) CHARACTER SET LATIN CASESPECIFIC TITLE '简历' NOT NULL,
      BOARD_SORT CHAR(2) CHARACTER SET LATIN CASESPECIFIC TITLE '板块类别' NOT NULL,
      S_DATE DATE FORMAT 'YYYYMMDD' TITLE '开始日期' NOT NULL,
      E_DATE DATE FORMAT 'YYYYMMDD' TITLE '结束日期' NOT NULL)
PRIMARY INDEX ( COMP_CDE ,EMPL_NAME ,S_DATE );
